backend:
  name: git-gateway
  # name: test-repo
  branch: main
media_folder: 'public/img'
public_folder: '/img'
slug:
  encoding: 'ascii'
  clean_accents: true
  sanitize_replacement: '_'

collections:
  - name: 'pages'
    label: 'Pages'
    files:
      - label: 'Home'
        name: 'home'
        file: 'content/home.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string', required: true }
          - { label: 'Publish Date', name: 'date', widget: 'datetime' , required: true}
          - { label: 'Body', name: 'body', widget: 'markdown' , required: true}
          - label: 'About'
            name: 'About'
            widget: 'list'
            fields:
                - {label: Image, name: image, widget: image, required: true}
                - {label: description, name: description, widget: string, required: true}
                - {label: Name, name: name, widget: string, required: true}
                - {label: Role, name: role, widget: string, required: true}
          - label: "Products"
            name: "products"
            widget: "list"
            fields:
                 - {label: Image, name: image, widget: image, required: true}
                 - {label: Title, name: title, widget: string, required: true}
                 - {label: Url, name: url, widget: string, required: true}
                 - {label: description, name: description, widget: string, required: true}
      - label: 'About'
        name: 'about'
        file: 'content/about.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Publish Date', name: 'date', widget: 'datetime' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
  - label: 'Blog'
    name: 'blog'
    folder: 'content/blogPosts'
    create: true
    slug: '{{year}}-{{month}}-{{day}}_{{title}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Seo-Description', name: 'seo_description', widget: 'string', required: true }
      - { label: 'Seo-keywords', name: 'seo_keywords', widget: 'string', required: true }
      - { label: 'Seo-title', name: 'seo_title', widget: 'string', required: true }
      - { label: 'Author', name: 'author', widget: 'string'}
      - { label: 'Read-minute', name: 'read_minute', widget: 'number', required: true }
      - { label: 'Publish Date', name: 'date', widget: 'datetime', required: true }
      - { label: 'Featured Image', name: 'thumbnail', widget: 'image', required: true }
      - { label: 'Body', name: 'body', widget: 'markdown', required: true }